service: aws-meow-bot
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

package:
  patterns:
    - '!img/**'
    - '!tests/**'

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
